services:
  backend:
    build:
      context: ./backend
    ports:
      - "8000:8000"
    networks:
      - soraka-network
    restart: always

  frontend:
    build:
      context: ./frontend
    ports:
      - "3000:3000"
    networks:
      - soraka-network
    depends_on:
      - backend
    restart: always
    tty: true # <-- AGREGA ESTA LÍNEA AQUÍ PARA MANTENER VIVO REACT
    
networks:
  soraka-network:
    driver: bridge